{
    "name": "ShipStation Odoo Integration",
    "version": "13.0",
    "category": "Sales",
    'summary': 'Integrate & Manage your ShipStation Operations from Odoo',

    "depends": ["stock", "delivery"],

    'data': [
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'views/shipstation_accounts_view.xml',
        'wizard/import_export_operation_view.xml',
        'views/shipstation_marketplaces_view.xml',
        'views/shipstation_stores_view.xml',
        'views/web_template.xml',
        'wizard/carrier_add_funds_view.xml',
        # 'wizard/prepare_order_for_shipstation_view.xml',
        'views/shipstation_carrier_view.xml',
        'views/dashboard_view.xml',
        'views/res_partner_view.xml',
        'views/shipstation_warehouse_view.xml',
        'views/shipstation_service_view.xml',
        'views/shipstation_product_view.xml',
        'views/sale_order_view.xml',
        'views/shipstation_package_view.xml',
        'views/delivery_carrier_view.xml',
        'security/ir.model.access.csv'
    ],

    'images': ['static/description/shipstation_odoo.png'],

    "author": "Teqstars",
    "website": "https://teqstars.com",
    'support': 'support@teqstars.com',
    'maintainer': 'Teqstars',
    "description": """
          ShipStation,
          Manage your Shipstation operation from Odoo,
          Integration Shipstation,
          Connector Shipstation,
          Shipstation Connector,
          Odoo Shipstation Connector,
          Shipstation integration,
          Shipstation odoo connector,
          Shipstation odoo integration,
          shipstation integration woocommerce,
          shipstation integration with shopify,	
          shipstation integration with quickbooks,
          shipstation integration with wix,
          shipstation integration with amazon,
          shipstation integration with ups,
          shipstation salesforce integration,
          shipstation amazon integration,
          shipstation cin7 integration,
          shipstation activecampaign integration,
          commercehub shipstation integration,
          shipstation ebay integration ,
          shipstation endicia integration,
          shipstation erp integration,
          shipstation magento 2 integration,
          odoo integration apps,
          odoo amazon integration,
          odoo ebay integration,
          odoo ecommerce integration,
          odoo fedex integration,
          odoo integration with shopify,
          odoo integration with salesforce,
          teqstars,
          TeqStars,
        """,

    'demo': [],
    'license': 'OPL-1',
    'auto_install': False,
    "installable": True,
    'application': True,
    'qweb': ['static/src/xml/shipstation_dashboard_template.xml'],
    "price": "99.99",
    "currency": "EUR",
}
